# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

demo = User.create({username: "derek", password:"123456", email:"123@aol.com", gender:"male", age: 8});


track1 = Track.create({title: "underground1", album: "none", artist_id: 1 })
track2 = Track.create({title: "underground2" , album: "none", artist_id: 1 })
track3 = Track.create({title: "underground3" , album: "none", artist_id: 1 })
track4 = Track.create({title: "underground4" , album: "none", artist_id: 1 })
track5 = Track.create({title: "underground5" , album: "none", artist_id: 1 })
track6 = Track.create({title: "underground6" , album: "none", artist_id: 1 })
track7 = Track.create({title: "underground7" , album: "none", artist_id: 1 })
track8 = Track.create({title: "underground8" , album: "none", artist_id: 1 })
track9 = Track.create({title: "underground9" , album: "none", artist_id: 1 })
track10 = Track.create({title: "underground10" , album: "none", artist_id: 1 })
track11 = Track.create({title: "underground11" , album: "none", artist_id: 1 })
track12 = Track.create({title: "underground12" , album: "none", artist_id: 1 })
track13 = Track.create({title: "underground13" , album: "none", artist_id: 1 })
track14 = Track.create({title: "underground14" , album: "none", artist_id: 1 })
track15 = Track.create({title: "underground15" , album: "none", artist_id: 1 })
track16 = Track.create({title: "underground16" , album: "none", artist_id: 1 })
track17 = Track.create({title: "underground17" , album: "none", artist_id: 1 })
track18 = Track.create({title: "underground18" , album: "none", artist_id: 1 })
track19 = Track.create({title: "underground19" , album: "none", artist_id: 1 })
track20 = Track.create({title: "underground20" , album: "none", artist_id: 1 })



audio_file1 = open(Rails.root.join('app', 'assets', 'tracks', 'Tau.mp3'))
audio_file3 = open(Rails.root.join('app', 'assets', 'tracks', 'Tau.mp3'))
audio_file7 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file8 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file11 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file12 = open(Rails.root.join('app', 'assets', 'tracks', 'Gizeh - Original Mix.mp3'))
audio_file6 = open(Rails.root.join('app', 'assets', 'tracks', 'Gizeh - Original Mix.mp3'))
audio_file13 = open(Rails.root.join('app', 'assets', 'tracks', 'Gizeh - Original Mix.mp3'))
audio_file14 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file15 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file16 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file17 = open(Rails.root.join('app', 'assets', 'tracks', '01 Esente (Original Mix).mp3'))
audio_file18 = open(Rails.root.join('app', 'assets', 'tracks', '02 le grand dome.mp3'))
audio_file19 = open(Rails.root.join('app', 'assets', 'tracks', '03 Effect (Original Mix).mp3'))

audio_file5 = open(Rails.root.join('app', 'assets', 'tracks', '03 Effect (Original Mix).mp3'))
audio_file4 = open(Rails.root.join('app', 'assets', 'tracks', '02 le grand dome.mp3'))
audio_file2 = open(Rails.root.join('app', 'assets', 'tracks', '01 Esente (Original Mix).mp3'))
audio_file9 = open(Rails.root.join('app', 'assets', 'tracks', 'Gizeh - Original Mix.mp3'))
audio_file10 = open(Rails.root.join('app', 'assets', 'tracks', 'Hugo Oak, Satori (NL) - Shoeless feat. Hugo Oak (Original Mix)101bpm.mp3'))
audio_file20 = open(Rails.root.join('app', 'assets', 'tracks', 'Tau.mp3'))

track1.audio_file.attach({io: audio_file1, filename: "MGAD1" })
track2.audio_file.attach({io: audio_file2, filename: "MGAD2" })
track3.audio_file.attach({io: audio_file3, filename: "MGAD3" })
track4.audio_file.attach({io: audio_file4, filename: "MGAD4" })
track5.audio_file.attach({io: audio_file5, filename: "MGAD5" })
track6.audio_file.attach({io: audio_file6, filename: "MGAD1235" })
track7.audio_file.attach({io: audio_file7, filename: "MGAD235" })
track8.audio_file.attach({io: audio_file8, filename: "MGAD6" })
track9.audio_file.attach({io: audio_file9, filename: "MGAD7" })
track10.audio_file.attach({io: audio_file10, filename: "MGA8D" })
track11.audio_file.attach({io: audio_file11, filename: "MGA52345D" })
track12.audio_file.attach({io: audio_file12, filename: "MGA456745D" })
track13.audio_file.attach({io: audio_file13, filename: "MGAsdfgsfD" })
track14.audio_file.attach({io: audio_file14, filename: "MGAsdfgsdfgD" })
track15.audio_file.attach({io: audio_file15, filename: "MGAsdfgsdfgD" })
track16.audio_file.attach({io: audio_file16, filename: "MGdgfhdfhfghAD" })
track17.audio_file.attach({io: audio_file17, filename: "MGAjfghjfghjD" })
track18.audio_file.attach({io: audio_file18, filename: "MGwertfsvAD" })
track19.audio_file.attach({io: audio_file19, filename: "MGsdgfsdfgsAD" })
track20.audio_file.attach({io: audio_file20, filename: "MGAsdfgsjtyrhtyhtD" })

imagefile1 = open(Rails.root.join('app', 'assets', 'images', 'IMG_0070.JPG'))
imagefile2 = open(Rails.root.join('app', 'assets', 'images', 'IMG_3179.jpg'))
imagefile3 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5373.jpg'))
imagefile4 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5374.jpg'))
imagefile5 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile6 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile7 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile8 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile9 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile10 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile11 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile12 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile13 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile14 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile15 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile16 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile17 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile18 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile19 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))
imagefile20 = open(Rails.root.join('app', 'assets', 'images', 'IMG_5377.jpg'))

track1.image_file.attach({io: imagefile1, filename: "MGasdfAD1" })
track2.image_file.attach({io: imagefile2, filename: "MGAasdfasdfD1" })
track3.image_file.attach({io: imagefile3, filename: "saMGAdsfgD1" })
track4.image_file.attach({io: imagefile4, filename: "MGafsdaAD1" })
track5.image_file.attach({io: imagefile5, filename: "MGAfasdfD1" })
track6.image_file.attach({io: imagefile6, filename: "MGAasdgdD1" })
track7.image_file.attach({io: imagefile7, filename: "MGAasdfD1" })
track8.image_file.attach({io: imagefile8, filename: "MGAasdfasdfD1" })
track9.image_file.attach({io: imagefile9, filename: "MGADasdfasdfas1" })
track10.image_file.attach({io: imagefile10, filename: "MGAasgdsfhdD1" })
track11.image_file.attach({io: imagefile11, filename: "MGsdfhsdfhAD1" })
track12.image_file.attach({io: imagefile12, filename: "MGAsdfhdsfhdD1" })
track13.image_file.attach({io: imagefile13, filename: "MGAsdfhsD1" })
track14.image_file.attach({io: imagefile14, filename: "MGAsdfhsdfhD1" })
track15.image_file.attach({io: imagefile15, filename: "MGAsdfhsdD1" })
track16.image_file.attach({io: imagefile16, filename: "MGAhsdfshdfD1" })
track17.image_file.attach({io: imagefile17, filename: "MGAhsdfhsD1" })
track18.image_file.attach({io: imagefile18, filename: "MGAdfhsdhfD1" })
track19.image_file.attach({io: imagefile19, filename: "MGasdfasdfasAD1" })
track20.image_file.attach({io: imagefile20, filename: "MGAdfasdfasdfasdfD1" })

comment1 = Comment.create({author_id: 1, track_id: 1, body: "nice"})
comment2 = Comment.create({author_id: 1, track_id: 2, body: "sweet!"})
comment3 = Comment.create({author_id: 1, track_id: 3, body: "cool"})
comment4 = Comment.create({author_id: 1, track_id: 4, body: "awesome"})
comment5 = Comment.create({author_id: 1, track_id: 5, body: "amazing"})
comment6 = Comment.create({author_id: 1, track_id: 6, body: "beautiful"})
comment7 = Comment.create({author_id: 1, track_id: 7, body: "lovely!"})
comment8 = Comment.create({author_id: 1, track_id: 8, body: "melodies"})
comment9 = Comment.create({author_id: 1, track_id: 9, body: "rhythm"})
comment10 = Comment.create({author_id: 1, track_id: 10, body: "structure"})
comment11 = Comment.create({author_id: 1, track_id: 11, body: "balance"})
comment12 = Comment.create({author_id: 1, track_id: 12, body: "awesome"})
comment13 = Comment.create({author_id: 1, track_id: 13, body: "so great"})
comment14 = Comment.create({author_id: 1, track_id: 14, body: "so smooth"})
comment15 = Comment.create({author_id: 1, track_id: 15, body: "hard!"})
comment16 = Comment.create({author_id: 1, track_id: 16, body: "dancing!!!!!!!!"})
comment17 = Comment.create({author_id: 1, track_id: 17, body: "chillllll"})
comment18 = Comment.create({author_id: 1, track_id: 18, body: "sweeeeeeet"})
comment19 = Comment.create({author_id: 1, track_id: 19, body: "wowwwwwwwwww"})
comment20 = Comment.create({author_id: 1, track_id: 20, body: "oooeeeeeeeee"})